# Generated by Django 5.2.5 on 2025-09-08 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardFightRegis', '0005_competition_competitionregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardFightRegis.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardFightRegis.deck')),
            ],
            options={
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
