# Generated by Django 5.2.5 on 2025-09-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardFightRegis', '0007_card_grade_card_nation_card_power_card_shield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Normal-Unit', 'Normal-Unit'), ('Trigger-Unit', 'Trigger-Unit'), ('G-Guardian', 'G-Guardian'), ('G-Unit', 'G-Unit'), ('Normal-Order', 'Normal-Order'), ('Set-Order', 'Set-Order'), ('Blitz-Order', 'Blitz-Order'), ('Trigger-Order', 'Trigger-Order')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Grade 0'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4')], null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='nation',
            field=models.CharField(choices=[('Keter Sanctuary', 'Keter Sanctuary'), ('Dragon Empire', 'Dragon Empire'), ('Stoicheia', 'Stoicheia'), ('Dark State', 'Dark State'), ('Brandt Gate', 'Brandt Gate'), ('Lyrical Monasterio', 'Lyrical Monasterio'), ('No Nation', 'No Nation')], max_length=50, null=True),
        ),
    ]
