# Generated by Django 5.2.5 on 2025-09-16 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardFightRegis', '0008_competitionregistration_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardFightRegis.deck'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='fee_slip',
            field=models.FileField(blank=True, null=True, upload_to='fee_slips/'),
        ),
    ]
